openapi: 3.0.3
info:
    title: GFE REST Services
    description: |
        REST services for curating and computing with GFE
    version: 2.0.0
    contact:
        email: cibmtr-pypi@nmdp.org
    license:
        name: GNU Lesser General Public License version 3
        url: https://opensource.org/licenses/lgpl-3.0.html
servers:
    -   url: 'http://localhost:8080'
tags:
    -   name: IMGT
        description: "Available IMGT DB releases"
    -   name: GFE
        description: Create and Retrieve GFE
    -   name: "Sequence Annotation"
        description: Annotation by sequence
paths:
    /imgt-versions:
        get:
            summary: IMGT DB versions in the DB
            tags:
                - IMGT
            operationId: api.imgt_versions
            description: Versions of IMGT DB Alleles in GFE DB

            responses:
                200:
                    description: Version Numbers of Available IMGT DB
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    imgt_versions:
                                        description: IMGT DB Versions
                                        type: array
                                        items:
                                            type: string
                                        example:
                                            - "3450"
                                            - "3460"
                                            - "3470"
                404:
                    description: "Failed to load all db releases"

    /who/{who_name}:
        get:
            summary: Get GFE for a WHO name
            tags:
                - GFE
            operationId: api.gfe_from_who
            description: For a given WHO Allele name, return the corresponding GFE
            parameters:
                -   name: who_name
                    in: path
                    description: WHO Allele name
                    required: true
                    schema:
                        type: string
                    style: simple
                    example: "HLA-A*01:01:01:08"
            responses:
                200:
                    description: GFE from WHO allele name
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    locus:
                                        description: Gene Locus
                                        type: string
                                        example: "HLA-A"
                                    gfe:
                                        description: GFE Name
                                        type: string
                                        example: "HLA-Aw878-8-363-912-830-2901-1044-581-151-324-198-9-316-80-508-43-151"
                                    who:
                                        description: WHO Name
                                        type: string
                                        example: "HLA-A*01:01:01:08"
                                    imgt_versions:
                                        description: IMGT Versions
                                        type: array
                                        items:
                                            type: string
                                        example:
                                            - "3460"
                                            - "3470"

    /gfe/locus/{gene}:
        get:
            summary: GFEs and WHO Names for a gene
            tags:
                - GFE
            operationId: api.all_locus_gfe
            description: Get all GFEs and WHO Names for a gene
            parameters:
                -   name: gene
                    in: path
                    description: WHO Gene Name
                    required: true
                    schema:
                        type: string
                    style: simple
                    example: "HLA-A"
            responses:
                200:
                    description: List of WHO allele names and their corresponding GFEs
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    locus:
                                        description: Gene Locus
                                        type: string
                                        example: "HLA-A"
                                    GFEs:
                                        description: List of WHO alleles and GFE
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                gfe:
                                                    description: GFE Name
                                                    type: string
                                                    example: "HLA-Aw878-8-363-912-830-2901-1044-581-151-324-198-9-316-80-508-43-151"
                                                who:
                                                    description: WHO Allele Name
                                                    type: string
                                                    example: "HLA-A*01:01:01:08"

    /gfe/sequence/{gfe}:
        get:
            summary: Sequence For a GFE
            tags:
                - GFE
            operationId: api.gfe_sequence
            description: Get Sequence for a GFE
            parameters:
                - name: gfe
                  in: path
                  description: GFE name
                  required: true
                  schema:
                      type: string
                  style: simple
                  example: "HLA-Aw99-8-363-912-830-2901-128-581-151-324-198-9-316-80-508-43-30"
            responses:
                200:
                    description: Sequence corresponding to a GFE
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    gfe:
                                        description: GFE
                                        type: string
                                        example: "HLA-Aw99-8-363-912-830-2901-128-581-151-324-198-9-316-80-508-43-30"
                                    sequence:
                                        description: Sequence for the GFE
                                        type: string
                                        example: "CAGGAGCAGAGGGGTCAGGGCGAAGTCCCAGGGCCCCAGGCGTGGCTCTCAGGGTCTCAGGCCCCGAAGGCGGTGTATGGATTGGGGAGTCCCAGCCTTGGGGATTCCCCAACTCCGCAGTTTCTTTTCTCCCTCTCCCAACCTACGTAGGGTCCTTCATCCTGGATACTCACGACGCGGACCCAGTTCTCACTCCCATTGGGTGTCGGGTTTCCAGAGAAGCCAATCAGTGTCGTCGCGGTCGCTGTTCTAAAGTCCGCACGCACCCACCGGGACTCAGATTCTCCCCAGACGCCGAGGATGGCCGTCATGGCGCCCCGAACCCTCCTCCTGCTACTCTCGGGGGCCCTGGCCCTGACCCAGACCTGGGCGGGTGAGTGCGGGGTCGGGAGGGAAACCGCCTCTGCGGGGAGAAGCAAGGGGCCCTCCTGGCGGGGGCGCAGGACCGGGGGAGCCGCGCCGGGAGGAGGGTCGGGCAGGTCTCAGCCACTGCTCGCCCCCAGGCTCCCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTATTGGGACCAGGAGACACGGAATATGAAGGCCCACTCACAGACTGACCGAGCGAACCTGGGGACCCTGCGCGGCTACTACAACCAGAGCGAGGACGGTGAGTGACCCCGGCCCGGGGCGCAGGTCACGACCCCTCATCCCCCACGGACGGGCCAGGTCGCCCACAGTCTCCGGGTCCGAGATCCACCCCGAAGCCGCGGGACTCCGAGACCCTTGTCCCGGGAGAGGCCCAGGCGCCTTTACCCGGTTTCATTTTCAGTTTAGGCCAAAAATCCCCCCGGGTTGGTCGGGGCGGGGCGGGGCTCGGGGGACTGGGCTGACCGCGGGGTCGGGGCCAGGTTCTCACACCATCCAGATAATGTATGGCTGCGACGTGGGGCCGGACGGGCGCTTCCTCCGCGGGTACCGGCAGGACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCTTGGACCGCGGCGGACATGGCAGCTCAGATCACCAAGCGCAAGTGGGAGGCGGTCCATGCGGCGGAGCAGCGGAGAGTCTACCTGGAGGGCCGGTGCGTGGACGGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCACGGGTACCAGGGGCCACGGGGCGCCTCCCTGATCGCCTATAGATCTCCCGGGCTGGCCTCCCACAAGGAGGGGAGACAATTGGGACCAACACTAGAATATCACCCTCCCTCTGGTCCTGAGGGAGAGGAATCCTCCTGGGTTTCCAGATCCTGTACCAGAGAGTGACTCTGAGGTTCCGCCCTGCTCTCTGACACAATTAAGGGATAAAATCTCTGAAGGAGTGACGGGAAGACGATCCCTCGAATACTGATGAGTGGTTCCCTTTGACACCGGCAGCAGCCTTGGGCCCGTGACTTTTCCTCTCAGGCCTTGTTCTCTGCTTCACACTCAATGTGTGTGGGGGTCTGAGTCCAGCACTTCTGAGTCTCTCAGCCTCCACTCAGGTCAGGACCAGAAGTCGCTGTTCCCTTCTCAGGGAATAGAAGATTATCCCAGGTGCCTGTGTCCAGGCTGGTGTCTGGGTTCTGTGCTCTCTTCCCCATCCCGGGTGTCCTGTCCATTCTCAAGATGGCCACATGCGTGCTGGTGGAGTGTCCCATGACAGATGCAAAATGCCTGAATTTTCTGACTCTTCCCGTCAGACCCCCCCAAGACACATATGACCCACCACCCCATCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACGGAGCTCGTGGAGACCAGGCCTGCAGGGGATGGAACCTTCCAGAAGTGGGCGGCTGTGGTGGTGCCTTCTGGAGAGGAGCAGAGATACACCTGCCATGTGCAGCATGAGGGTCTGCCCAAGCCCCTCACCCTGAGATGGGGTAAGGAGGGAGATGGGGGTGTCATGTCTCTTAGGGAAAGCAGGAGCCTCTCTGGAGACCTTTAGCAGGGTCAGGGCCCCTCACCTTCCCCTCTTTTCCCAGAGCTGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCATTGCTGGCCTGGTTCTCCTTGGAGCTGTGATCACTGGAGCTGTGGTCGCTGCCGTGATGTGGAGGAGGAAGAGCTCAGGTGGAGAAGGGGTGAAGGGTGGGGTCTGAGATTTCTTGTCTCACTGAGGGTTCCAAGCCCCAGCTAGAAATGTGCCCTGTCTCATTACTGGGAAGCACCTTCCACAATCATGGGCCGACCCAGCCTGGGCCCTGTGTGCCAGCACTTACTCTTTTGTAAAGCACCTGTTAAAATGAAGGACAGATTTATCACCTTGATTACGGCGGTGATGGGACCTGATCCCAGCAGTCACAAGTCACAGGGGAAGGTCCCTGAGGACAGACCTCAGGAGGGCTATTGGTCCAGGACCCACACCTGCTTTCTTCATGTTTCCTGATCCCGCCCTGGGTCTGCAGTCACACATTTCTGGAAACTTCTCTGGGGTCCAAGACTAGGAGGTTCCTCTAGGACCTTAAGGCCCTGGCTCCTTTCTGGTATCTCACAGGACATTTTCTTCCCACAGATAGAAAAGGAGGGAGTTACACTCAGGCTGCAAGTAAGTATGAAGGAGGCTGATGCCTGAGGTCCTTGGGATATTGTGTTTGGGAGCCCATGGGGGAGCTCACCCACCCCACAATTCCTCCTCTAGCCACATCTTCTGTGGGATCTGACCAGGTTCTGTTTTTGTTCTACCCCAGGCAGTGACAGTGCCCAGGGCTCTGATGTGTCTCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGGCCTGATGTGTGTTGGGTGTTGGGTGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCGTTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAGAGGCAAGAGTTGTTCCTGCCCTTCCCTTTGTGACTTGAAGAACCCTGACTTTGTTTCTGCAAAGGCACCTGCATGTGTCTGTGTTCGTGTAGGCATAATGTGAGGAGGTGGGGAGAGCACCCCACCCCCATGTCCACCATGACCCTCTTCCCACGCTGACCTGTGCTCCCTCTCCAATCATCTTTCCTGTTCCAGAGAGGTGGGGCTGAGGTGTCTCCATCTCTGTCTCAACTTCATGGTGCACTGAGCTGTAACTTCTTCCTTCCCTATTAAAA"
